### PR TITLE
fix colorization of fields in editor

### LINKED ISSUE #3: Colours not working in add window

### PR DESCRIPTION
**Pull request by kieranlblack**
The primary issue was that the way the tone css was being injected no longer worked for the current version of Anki. This commit modifies things to inject css in the proper manner.

image

Closes #3.

### CODE REVIEW

**Comment by Gustaf-C** [comment]
A small issue I found is that if I open the add notes window, and a note type without the tone colours css is opened by default, if I then switch to a note type with the tone colours css it won't show the colours in the editor window unless I close and reopen the window.

The number of times this would actually be an issue should be quite small, although it is a bit confusing.

**Comment by kieranlblack** [comment]
Hmm, would you mind sending a gif of the behaviour. I'm having difficulty reproducing the issue, this seems to be what you are describing:

There does actually seem to be some sort of issue with the font though.

demo

**Comment by Gustaf-C** [comment]
Recording

**Comment by kieranlblack** [comment]
I see, good catch. I have been able to reproduce the issue, I will look into what is causing it.

**Comment by kieranlblack** [comment]
The components are not being remounted so the `onMount` hook where we inject the styling is not being refired. This seems like it might be a bug in Anki, when the custom styling changes it should trigger a remount, I will continue looking tomorrow if I have time.

**Comment by kieranlblack** [comment]
I have made a little progress, the css should now definitely update and you won't see the bug you were seeing before. However, there is a race condition which has stumped me causing the `userBase` css to sometimes get wiped out resulting in most noticeably the font family and size not getting set correctly in the editor.

You can see it looks kind of strange here:

image

**Comment by kieranlblack** [comment]
Made a post about this on the forums.

https://forums.ankiweb.net/t/customstyles-strange-behaviour/37432

**Comment by Gustaf-C** [comment]
Good idea, hopefully some anki guru will come with some input. I tried looking at it for a while yesterday, but js isn't really my strong suit.

**Comment by kieranlblack** [comment]
It looks like nobody has weighed in on the post I made yet. I think I'm going to implement the fix I had in the post and then open a PR for Anki and see what dae thinks there.

**Comment by Gustaf-C** [comment]
Sounds good. 

Otherwise I suggest we revert to 7faaf71 since that was at least an improvement, and then log the remaining bug in a new issue.

**Comment by kieranlblack** [comment]
@Gustaf-C just as a heads up, the fix for the issue with the custom style in Anki was merged in the other day so when the next Anki release is cut we should be able to merge this PR in 🥳

**Comment by kieranlblack** [comment]
@Gustaf-C Ah, I guess I probably would've waited to avoid introducing known buggy code. We don't really know when the next Anki version will drop and now we are in a position where any bug fixes / features we want to push before it does will include this change unless we add a version check.

**Comment by Gustaf-C** [comment]
Yeah I know that it might become problematic in some cases, but it's the easiest way for me to make sure that the addon works well with the latest Anki version. If we want to push something else before the next Anki release I'll figure it out when we get there. If I regret doing it I'll just remember that the next time :)

**Pull request merged**
